name: Bug Report
description: Create a report to help us improve.
labels: [bug]
body:
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
